"""empty message

Revision ID: 7f08b6f6aa3a
Revises: 32b365683ee9
Create Date: 2024-09-14 02:36:06.717759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f08b6f6aa3a'
down_revision = '32b365683ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=42), nullable=False),
    sa.Column('ki', sa.Integer(), nullable=False),
    sa.Column('race', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
